### ISSUE TITLE
Systemd hates trailing comments

### ISSUE THREAD

**Issue by pl77** [fabwu/jdownloader-install#1]
Just as an FYI, after fighting with my jdownloader.service file for far too long I discovered that systemd refuses to process trailing comments.  But it doesn't tell you that.  That would be too logical.  Instead it says:

```Subject: Process /usr/bin/java could not be executed```

...which results in a person chasing the wrong symptoms for the better part of an hour.  

There.  Now I feel better.  👍

**Comment by pl77** [comment]
Also, this was an awesome tutorial and I appreciated it greatly.  thank you for pulling it together, now it's working perfectly!

**Comment by fabwu** [comment]
Thanks I didn't realized that because my service file has no comments. I moved the trailing comments to a new line above.
