### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by diyfr** [fabwu/jdownloader-install#2]
replace 
```bash
sudo mv jdownloader.jar /opt/jdownloader
```
by  

```bash
sudo mv Jdownloader.jar /opt/jdownloader
```
Thanks  for this script !
I found another installation by docker [here](https://github.com/jlesage/docker-jdownloader-2), it can work without MyJowndoader

**Comment by fabwu** [comment]
Sorry I can't see any difference between your commands.

Thanks for sharing the docker image.

**Comment by simonerni** [comment]
The J from Jdownloader should be big :)

**Comment by fabwu** [comment]
@simonerni Thanks I fixed it. Our photos look so similar... 🤔

**Comment by simonerni** [comment]
They do! Did we go to the same photographer per chance? 🤔
